scriptencoding=utf-8

" https://github.com/junegunn/vim-plug
silent! call plug#begin('~/.vim/plugged')

Plug 'morhetz/gruvbox'
Plug 'rodjek/vim-puppet'
Plug 'ekalinin/Dockerfile.vim'
Plug 'joereynolds/vim-minisnip'

" scrooloose/nerdtree {{{
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
let g:NERDTreeShowHidden=1
let g:NERDTreeQuitOnOpen = 1
let g:NERDTreeAutoDeleteBuffer = 1
let g:NERDTreeMinimalUI = 1
let g:NERDTreeDirArrows = 1
nnoremap <C-\> :NERDTreeToggle<CR>
" }}}

" vim-airline/vim-airline {{{
Plug 'vim-airline/vim-airline'
let g:airline_theme='gruvbox'
let g:airline_extensions = ['tabline']
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_splits = 1
let g:airline#extensions#tabline#show_buffers = 0
let g:airline#extensions#tabline#show_tabs = 1
let g:airline#extensions#tabline#show_close_button = 0
let g:airline#extensions#tabline#show_tab_count = 0
let g:airline#extensions#tabline#show_tab_nr = 1
let g:airline#extensions#tabline#tab_nr_type = 1
let g:airline#extensions#tabline#show_tab_type = 0
let g:airline#extensions#tabline#tab_min_count = 2
let g:airline#extensions#tabline#buffer_nr_show = 1
let g:airline#extensions#tabline#left_sep = ''
let g:airline#extensions#tabline#left_alt_sep = ''
let g:airline#extensions#tabline#right_sep = ''
let g:airline#extensions#tabline#right_alt_sep = ''
let g:airline#extensions#tabline#tabtitle_formatter = 'EmptyTabTitleFormatter'
function EmptyTabTitleFormatter(n)
	return ' '
endfunction
" }}}

" dense-analysis/ale {{{
Plug 'dense-analysis/ale'
let g:ale_linters_explicit = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_enter = 0
let g:ale_lint_on_save = 1
let g:ale_fix_on_save = 1
nnoremap <C-l>n :ALENext<CR>
nnoremap <C-l>N :ALEPrevious<CR>
nnoremap <C-l>l :ALELint<CR>
nnoremap <C-l>f :ALEFix<CR>
" }}}

" editorconfig/editorconfig-vim {{{
Plug 'editorconfig/editorconfig-vim'
let g:EditorConfig_max_line_indicator = 'line'
" }}}

call plug#end()

filetype plugin indent on
syntax on

" Disable arrow buttons file settings {{{
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
vnoremap <up> <nop>
vnoremap <down> <nop>
vnoremap <left> <nop>
vnoremap <right> <nop>
" }}}

set t_Co=256
silent! colorscheme gruvbox
set background=dark
set laststatus=2
set ruler
set showcmd

set number
set numberwidth=5
set scrolloff=5

set autoindent
set smartindent
set tabstop=4
set linebreak

" Encoding and hidden char {{{
set encoding=utf-8
set list
set listchars=tab:»\ ,trail:·,nbsp:·,eol:¬
if has("patch-7.4.710")
	set listchars=tab:»\ ,trail:·,nbsp:·,eol:¬,space:·
endif
set backspace=indent,eol,start
" }}}

" Unsorted options {{{
set foldmethod=manual
set nocompatible
set modifiable
set wrap
set incsearch
set hlsearch
set ignorecase
set nobackup
set noswapfile
set hidden
set wildmenu
set path+=**
" }}}
