scriptencoding=utf-8

" Plugins installed via https://github.com/junegunn/vim-plug
silent! call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
let g:NERDTreeShowHidden=1
let g:NERDTreeQuitOnOpen = 1
let g:NERDTreeAutoDeleteBuffer = 1
let g:NERDTreeMinimalUI = 1
let g:NERDTreeDirArrows = 1
nnoremap <C-\> :NERDTreeToggle<CR>

Plug 'morhetz/gruvbox'
Plug 'rodjek/vim-puppet'
Plug 'ekalinin/Dockerfile.vim'
Plug 'joereynolds/vim-minisnip'

Plug 'dense-analysis/ale'
let g:ale_linters_explicit = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_enter = 0
let g:ale_lint_on_save = 1
let g:ale_fix_on_save = 1
nnoremap <C-l>n :ALENext<CR>
nnoremap <C-l>N :ALEPrevious<CR>
nnoremap <C-l>l :ALELint<CR>
nnoremap <C-l>f :ALEFix<CR>

Plug 'editorconfig/editorconfig-vim'
let g:EditorConfig_max_line_indicator = 'line'

call plug#end()

filetype plugin indent on
syntax on

" Disable arrow buttons
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
vnoremap <up> <nop>
vnoremap <down> <nop>
vnoremap <left> <nop>
vnoremap <right> <nop>

" Disable <Esc> for exit. Use <c-c>
" inoremap <Esc> <nop>
" vnoremap <Esc> <nop>

set t_Co=256
silent! colorscheme gruvbox
set background=dark
set laststatus=2
set ruler
set showcmd

set number
set numberwidth=5
set scrolloff=5

set autoindent
set smartindent
set tabstop=4
set linebreak

set encoding=utf-8
set list
set listchars=tab:»\ ,trail:·,nbsp:·,eol:¬
if has("patch-7.4.710")
	set listchars=tab:»\ ,trail:·,nbsp:·,eol:¬,space:·
endif
set backspace=indent,eol,start

set nocompatible
set modifiable
set wrap
set incsearch
set hlsearch
set ignorecase
set nobackup
set noswapfile
set hidden
set wildmenu
set path+=**
